// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CouponUIClient is the client API for CouponUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponUIClient interface {
	// ListEngineSpecs returns a list of Coupon Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CouponUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type couponUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponUIClient(cc grpc.ClientConnInterface) CouponUIClient {
	return &couponUIClient{cc}
}

func (c *couponUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CouponUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CouponUI_ServiceDesc.Streams[0], "/v1.CouponUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &couponUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CouponUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type couponUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *couponUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *couponUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CouponUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponUIServer is the server API for CouponUI service.
// All implementations must embed UnimplementedCouponUIServer
// for forward compatibility
type CouponUIServer interface {
	// ListEngineSpecs returns a list of Coupon Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, CouponUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCouponUIServer()
}

// UnimplementedCouponUIServer must be embedded to have forward compatible implementations.
type UnimplementedCouponUIServer struct {
}

func (UnimplementedCouponUIServer) ListEngineSpecs(*ListEngineSpecsRequest, CouponUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedCouponUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCouponUIServer) mustEmbedUnimplementedCouponUIServer() {}

// UnsafeCouponUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponUIServer will
// result in compilation errors.
type UnsafeCouponUIServer interface {
	mustEmbedUnimplementedCouponUIServer()
}

func RegisterCouponUIServer(s grpc.ServiceRegistrar, srv CouponUIServer) {
	s.RegisterService(&CouponUI_ServiceDesc, srv)
}

func _CouponUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CouponUIServer).ListEngineSpecs(m, &couponUIListEngineSpecsServer{stream})
}

type CouponUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type couponUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *couponUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CouponUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CouponUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouponUI_ServiceDesc is the grpc.ServiceDesc for CouponUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouponUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CouponUI",
	HandlerType: (*CouponUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CouponUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _CouponUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coupon-ui.proto",
}
